---
- name: Install HAProxy Load Balancer
  hosts: haproxy
  become: true
  tasks:
    - name: Install HAProxy package
      apt:
        name: haproxy
        state: present
    - name: Copy and replace file
      copy:
        src: ./haproxy.cfg
        dest: /etc/haproxy/haproxy.cfg
      notify: Restart haproxy
  handlers:
    - name: Restart haproxy
      service:
        name: haproxy
        state: restarted
- name: update package on webservers group
  hosts: webservers
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
    - name: Install apache httpd
      apt:
        name: apache2
        state: present
    - name: Copy and replace file
      copy:
        src: ./web-1.index.html
        dest: /var/www/html/index.html
